# Generated by Django 5.1.7 on 2025-04-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('size', models.CharField(choices=[('Tiny', 'Крошечный'), ('Small', 'Маленький'), ('Medium', 'Средний'), ('Large', 'Крупный')], max_length=10, verbose_name='размер')),
                ('friendliness', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='дружелюбность')),
                ('trainability', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='обучаемость')),
                ('shedding_amount', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='линька')),
                ('exercise_needs', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='физ. упражнения')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('age', models.PositiveIntegerField(verbose_name='возраст')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='пол')),
                ('color', models.CharField(max_length=100, verbose_name='цвет')),
                ('favorite_food', models.CharField(max_length=200, verbose_name='любимая еда')),
                ('favorite_toy', models.CharField(max_length=200, verbose_name='любимая игрушка')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='api.breed', verbose_name='порода')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
    ]
